### PR TITLE
Fix the iterators example.

### LINKED ISSUE #197: Readme for iterators exercise has typo which makes test fail
The solution for the "Iterators" exercise reads the lines from [this file](https://github.com/ferrous-systems/rust-exercises/blob/main/exercise-solutions/iterators/numbers.txt) but [the README](https://github.com/ferrous-systems/rust-exercises/blob/main/exercise-book/src/iterators.md#task) tells the user to create a file with the final '11' missing. This results in the sum_of_odd_numbers value being 20 instead of 31, causing a panic.

### PR DESCRIPTION
**Pull request by jonathanpallant**
Simplified the solution and tidied up some of the exercise text whilst I was here.

Closes #197

### CODE REVIEW

File: exercise-solutions/iterators/src/main.rs [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    let reader = BufReader::new(f);
+
+    let sum_of_odd_numbers: i32 = reader
+        .lines()
+        .filter_map(|line| line.ok())
+        .filter_map(|s| s.parse().ok())
+        .filter(|num| num % 2 != 0)
+        .fold(0, |acc, elem| acc + elem);
+        // Also works
+        //.sum::<i32>();
```
Comment (listochkin) [inline exercise-solutions/iterators/src/main.rs:16]: I would simply put `.sum();` here. Unlike `filter` and `map` that are popular, `fold` is not used too often. Half of `Itertools` methods are fold variants with more descriptive methods. May as well call `sum` because we work with numbers here. Turbofish is not needed, because there's `i32` on line 9 already.

```suggestion
        .sum();
```

Comment (jonathanpallant) [reply exercise-solutions/iterators/src/main.rs]:
```text
11 |     let result = reader.lines()
   |         ^^^^^^
...
15 |         .sum();
   |          --- type must be known at this point
```

oops

**Comment by jonathanpallant** [comment]
I have appeased the type checker.
